### ISSUE TITLE
Data set error

### ISSUE THREAD

**Issue by cswwp** [Lu-Feng/DHE-VPR#3]
Hi feng, thanks for your great work, and i am reproducing this work. Now i run eval according to readme, but it show an error like "Folder {gallery_folder} does not exist", and i check out this code ,and find no gallery in  pitts30k/pitts250k direction( which have been generated according by https://github.com/gmberton/VPR-datasets-downloader), any tips? thank you @Lu-Feng 

and my pitts30k dataset tree as follows:
![image](https://github.com/Lu-Feng/DHE-VPR/assets/11901683/ca1b2767-1c2c-4496-8545-2ecf3ab734ec)

**Comment by Lu-Feng** [comment]
Hello, thanks for your interest. The produced database is equivalent to gallery. You can rename database as gallery or create a soft link.
