### ISSUE TITLE
About compute_similarity

### ISSUE THREAD

**Issue by cswwp** [Lu-Feng/DHE-VPR#4]
Hi @Lu-Feng , i have a question about compute_similarity function in network.py, why do eatures_a.transpose(2, 3), in my thinking , the shape of features_a and feature_b both are n*c*h*w. seems your code do transpose(2, 3) with features_a, but no transform with features_b.
![image](https://github.com/Lu-Feng/DHE-VPR/assets/11901683/07b2831d-7be2-47c2-9a9d-5d7ff383c212)

**Comment by Lu-Feng** [comment]
Sorry for late reply. This function is based on the compute_similarity function of [GeoWarp](https://github.com/gmberton/geo_warp/blob/main/network.py). It seems that whether or not the transpose(2, 3) is performed does not make a significant difference. Performing features_a.transpose(2, 3) will only make a difference in the order of the elements in channel dimension in the similarity map (i.e. correlation_tensor), which will not have a significant impact on the subsequent use of it in the homography regression module. The network should be able to learn this order.

**Comment by cswwp** [comment]
> Sorry for late reply. This function is based on the compute_similarity function of [GeoWarp](https://github.com/gmberton/geo_warp/blob/main/network.py). It seems that whether or not the transpose(2, 3) is performed does not make a significant difference. Performing features_a.transpose(2, 3) will only make a difference in the order of the elements in channel dimension in the similarity map (i.e. correlation_tensor), which will not have a significant impact on the subsequent use of it in the homography regression module. The network should be able to learn this order.

In other words, does it mean no necessary to do transpose with feature_a, it's ok just keep consistency between train and test.

**Comment by Lu-Feng** [comment]
> > Sorry for late reply. This function is based on the compute_similarity function of [GeoWarp](https://github.com/gmberton/geo_warp/blob/main/network.py). It seems that whether or not the transpose(2, 3) is performed does not make a significant difference. Performing features_a.transpose(2, 3) will only make a difference in the order of the elements in channel dimension in the similarity map (i.e. correlation_tensor), which will not have a significant impact on the subsequent use of it in the homography regression module. The network should be able to learn this order.
> 
> In other words, does it mean no necessary to do transpose with feature_a, it's ok just keep consistency between train and test.

Yes, I think so. But I haven't verified it experimentally.
