### ISSUE TITLE
HomographyRegression output show 

### ISSUE THREAD

**Issue by cswwp** [Lu-Feng/DHE-VPR#5]
Have you tried to visualize the four points on query and reference image which generate by HomographyRegression？I try to show these four points on query and reference image in my local image which are resize to 383x384, but seems many points of these four points are out of image boundry(less than 0 or beyond 384), it this normal ? @Lu-Feng

**Comment by Lu-Feng** [comment]
The 4 points output by the Homography Regression module can be regarded as "pseudo" pixel coordinates. They cannot be directly used as the real pixel coordinates.
